# Generated by Django 2.2.1 on 2019-06-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['id', 'name'], 'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id', 'username'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
