# Generated by Django 2.2.1 on 2019-09-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/avatar/default.jpg', upload_to='avatar/%Y%m%d/'),
        ),
    ]
