# Generated by Django 2.2.1 on 2019-08-29 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_limit', models.FloatField(max_length=10, verbose_name='上限值')),
                ('l_limit', models.FloatField(max_length=10, verbose_name='下限值')),
                ('t_value', models.FloatField(max_length=10, verbose_name='目标值')),
                ('status', models.CharField(choices=[('using', '使用中'), ('unused', '未使用')], default='unused', max_length=32, verbose_name='状态')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_dep', to='account.Departments', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '部门KPI',
                'verbose_name_plural': '部门KPI',
                'ordering': ['id', 'dep'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('unit', models.CharField(max_length=32, verbose_name='单位')),
                ('in_time', models.CharField(max_length=32, verbose_name='录入时间')),
                ('mo_time', models.CharField(max_length=32, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('using', '使用中'), ('unused', '未使用')], default='unused', max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPI',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KpiInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_value', models.FloatField(max_length=10, verbose_name='实际值')),
                ('month', models.DateField(verbose_name='月份')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('groupkpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_group', to='kpimng.GroupKPI', verbose_name='部门KPI')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_user', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
            ],
            options={
                'verbose_name': 'KPI数据输入',
                'verbose_name_plural': 'KPI数据输入',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='groupkpi',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_kpi', to='kpimng.KPI', verbose_name='KPI'),
        ),
    ]
