# Generated by Django 2.2.1 on 2019-10-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpimng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupkpi',
            name='status',
            field=models.CharField(choices=[('using', '使用中'), ('unused', '未使用')], default='unused', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='status',
            field=models.CharField(choices=[('using', '使用中'), ('unused', '未使用')], default='unused', max_length=32, verbose_name='状态'),
        ),
    ]
