# Generated by Django 2.2.1 on 2019-08-14 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpimng', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupkpi',
            options={'ordering': ['id', 'dep'], 'verbose_name': '部门KPI', 'verbose_name_plural': '部门KPI'},
        ),
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['id', 'name'], 'verbose_name': 'KPI', 'verbose_name_plural': 'KPI'},
        ),
        migrations.AlterField(
            model_name='groupkpi',
            name='dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_dep', to='account.Departments', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='groupkpi',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_kpi', to='kpimng.KPI', verbose_name='KPI'),
        ),
        migrations.CreateModel(
            name='KpiInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_value', models.FloatField(max_length=10, verbose_name='实际值')),
                ('month', models.DateField(verbose_name='月份')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('groupkpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_group', to='kpimng.GroupKPI', verbose_name='部门KPI')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_user', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
            ],
            options={
                'verbose_name': 'KPI数据输入',
                'verbose_name_plural': 'KPI数据输入',
                'ordering': ['id'],
            },
        ),
    ]
