# Generated by Django 2.2.1 on 2019-10-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpimng', '0002_auto_20191014_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpiinput',
            options={'ordering': ['add_time'], 'verbose_name': 'KPI数据输入', 'verbose_name_plural': 'KPI数据输入'},
        ),
    ]
