# Generated by Django 2.2.1 on 2019-08-14 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpimng', '0002_auto_20190618_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupkpi',
            name='dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_dep', to='account.Departments', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='groupkpi',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_kpi', to='kpimng.KPI', verbose_name='KPI'),
        ),
        migrations.AlterField(
            model_name='kpiinput',
            name='groupkpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_group', to='kpimng.GroupKPI', verbose_name='部门KPI'),
        ),
        migrations.AlterField(
            model_name='kpiinput',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_user', to=settings.AUTH_USER_MODEL, verbose_name='录入人'),
        ),
    ]
